### ISSUE TITLE
Remove match when deleting player

### ISSUE THREAD

**Issue by tpokora** [tomek199/elo-rating-core#20]

**Comment by tomek199** [comment]
When deleting player remove matches from DB 
where `match.playerOne == deletedPlayer or match.playerTwo == deletedPlayer`

**Comment by tomek199** [comment]
https://jira.spring.io/browse/DATAMONGO-440

**Comment by tpokora** [comment]
@Query(value = "{'$or': [{'playerOne.id': ?0}, {'playerTwo.id': ?0}]}")
List<Match> findByPlayerId(String playerId);

causes:
com.mongodb.util.JSONParseException: 
{'$or': [{'playerOne.id': "58f2342a70135a22d5ea13e2"}, {'playerTwo.id': "58f2342a70135a22d5ea13e2"0}]}

function call commented out

**Comment by tomek199** [comment]
Problem was described here: http://stackoverflow.com/questions/43306460/spring-mongorepository-query-jsonparseexception. 
It works fine on my local and also on heroku deploy. 
Please make sure you have updated maven _spring-boot-starter-parent_ to **1.5.2.RELEASE**

**Comment by tpokora** [comment]
Works after reimporting maven dependencies, fixed NullPointerException when delete player
