### ISSUE TITLE
Change queue and match combination

### ISSUE THREAD

**Issue by tomek199** [tomek199/elo-rating-core#22]
Now the queue contains matches as objects array: 
![zrzut ekranu 2017-04-23 o 14 37 14](https://cloud.githubusercontent.com/assets/6180268/25313626/75a5ecb4-2832-11e7-928e-4b59c1b51352.png)

To avoid duplications in database, _queue_ collection should contains only references to matches using `@DBRef` annotation.

**Comment by tpokora** [comment]
@tomek199 
![ref](https://cloud.githubusercontent.com/assets/8877857/26599516/20b00578-4579-11e7-9f25-a6fb8ccdca7a.png)

is this correct? Just reference to match.
Top element in queue with match reference, 
Second element old way, match element in queue element

**Comment by tomek199** [comment]
Perfect 👍 
that's how it should be.
